<?php

/**
 * PluginImageReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImageReplyTable extends ImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImageReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImageReply');
    }
}