<?php

/**
 * PluginImagePointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImagePointTable extends ImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImagePointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImagePoint');
    }
}