<?php

/**
 * PluginImageAdvertTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginImageAdvertTable extends ImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginImageAdvertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginImageAdvert');
    }
}