detect_relations: true
options:
  type: INNODB
  charset: utf8

Image:
  tableName:   false
  actAs:
    SkipColumns: { skip: [bin] }
  columns:
    size:      { type: integer(8),  notnull: true }
    type:      { type: string(16),  notnull: true }
    bin:       { type: blob,        notnull: true }
  options:
    symfony:
      filter: false
      form:   false

ImagePoint:
  tableName: app_images_point
  inheritance:
    extends: Image
    type: concrete
  columns:
    point_id:  { type: integer, notnull: true }
  relations:
    Point:
      local: point_id
      foreign: id
      foreignType: many
      foreignAlias: Images
      onDelete: CASCADE
    Place:
      local: point_id
      foreign: id
      foreignType: many
      foreignAlias: Images
      onDelete: CASCADE
    Event:
      local: point_id
      foreign: id
      foreignType: many
      foreignAlias: Images
      onDelete: CASCADE
