detect_relations: true
options:
  type: INNODB
  charset: utf8

Image:
  tableName:   false
  actAs:
    SkipColumns: { skip: [bin] }
  columns:
    size:      { type: integer(8),  notnull: true }
    type:      { type: string(16),  notnull: true }
    bin:       { type: blob,        notnull: true }
  options:
    symfony:
      filter: false
      form:   false

ImageAdvert:
  tableName: board_images_advert
  inheritance:
    extends: Image
    type: concrete
  columns:
    advert_id:  { type: integer, notnull: true }
  relations:
    Advert:
      local: advert_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Images
      onDelete: CASCADE
